on: [push, pull_request]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'arduino:avr:uno'
          libraries: |
            - name: RTDModule
            - name: rtd
      - uses: actions/upload-artifact@v2
        with:
          name: sketches-reports
          path: sketches-reports
